### ISSUE TITLE
Les données et leurs sources sont listées

### ISSUE THREAD

**Issue by liZe** [Kozea/AlphaBet#2]

**Comment by Romlie** [comment]
**Fonctionnalités du site :**
-> se connecter 
-> voir les matchs passés et à venir (prochaines journées)
-> parier sur les matchs à venir
-> voir ses paris + résultats des matchs et paris
-> voir les paris des autres utilisateurs 

**Utilisation de l'API (football-data.org) :** 
lien vers matchs de la ligue 1 : http://api.football-data.org/v1/competitions/434/fixtures
Données à récupérer : 
-> homeTeam (lien)
-> awayTeam (lien)
-> date (DATE+T(ime)) (à parser)
-> status (FINISHED/TIMED/SCHEDULDED/POSTPONED)
-> match_id (fin url récupérer INT)
-> matchday (journée INT)
-> homeTeamName (STRING)
-> awayTeamName (STRING)
-> result (STRING : "goalsHomeTeam" + INT / STRING : "goalsAwayTeam" + INT) 
-> odds (STRING : "homeWin" + FLOAT / STRING : "draw" + FLOAT / STRING : "awayWin" + FLOAT)
