### ISSUE TITLE
Les données locales sont modélisées

### ISSUE THREAD

**Issue by liZe** [Kozea/AlphaBet#3]

**Comment by Maellepnt** [comment]
**Base de données SQLite3:**

CREATE TABLE users
(
  u_id integer PRIMARY KEY AUTOINCREMENT,
  username varchar(20) NOT NULL,
  password varchar(20) NOT NULL
);

CREATE TABLE user_bets
(
  id_bet integer PRIMARY KEY AUTOINCREMENT,
  u_id integer NOT NULL,
  match_id integer NOT NULL,
  outcome varchar(1),
  FOREIGN KEY (u_id) REFERENCES users(u_id),
  CONSTRAINT couple_unique UNIQUE (u_id, match_id)
);

![db](https://cloud.githubusercontent.com/assets/27198899/25170518/24fc82cc-24eb-11e7-89f7-1504c2f7890b.png)

**Comment by Romlie** [comment]
**Base de données SQLite :**


create table **users**
(
  u_id integer primary key autoincrement,
  username varchar(20) not null,
  password varchar(20) not null
);

create table **user_bets**
(
  id_bet integer primary key autoincrement,
  u_id integer not null,
  match_id integer not null,
  outcome varchar(1),
  FOREIGN KEY (u_id) REFERENCES users(u_id),
  CONSTRAINT couple_unique UNIQUE (u_id, match_id)
);

![db](https://cloud.githubusercontent.com/assets/25310926/25170533/320dd2a4-24eb-11e7-8718-dbb9308962a4.png)
